spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookcase-manager #change to 5432 if out of container
    username: postgres
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true #see all logs for executed queries
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true